import React, { Component } from 'react';
import Product from './Product'

export default class Cart extends Component{

state={
    products:[
        {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },
        {name:"products6",description:"Some quick example text to build on the card title and make up the bulk of the card's content.7",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products7",description:"Some quick example text to build on the card title and make up the bulk of the card's content.8",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },
        {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },  {name:"products1",description:"Some quick example text to build on the card title and make up the bulk of the card's content.1",prise:"2500",title:"title1",src:"1.jpeg" },
        {name:"products2",description:"Some quick example text to build on the card title and make up the bulk of the card's content.2",prise:"2500",title:"title1",src:"3.jpeg" },
        {name:"products3",description:"Some quick example text to build on the card title and make up the bulk of the card's content.3",prise:"2500",title:"title1",src:"4.jpeg" },
        {name:"products4",description:"Some quick example text to build on the card title and make up the bulk of the card's content.4",prise:"2500",title:"title1",src:"2.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.5",prise:"2500",title:"title1",src:"5.jpeg" },
        {name:"products5",description:"Some quick example text to build on the card title and make up the bulk of the card's content.6",prise:"2500",title:"title1",src:"6.jpeg" },
    ]
}

    render() {
        return (
            <>
             <div className='row container-fluid ms-0'>
            <h1 className="text-center bg-light fst-italic">Products Page</h1>
            <h6 className='abc'><span class="badge bg-secondary fs-5">{this.state.products.length}</span></h6>
           <Product Products={this.state.products}
           deletedata={this.deleteItem}
           />
           </div>
            </>
        );
    }
    deleteItem = (index) => {
		
		if(window.confirm("Are You sure ? To Delete")){
			
			var newProducts = [...this.state.products];	
		     console.log(newProducts)
			//console.log("delete product of",index);
			newProducts.splice(index,1);
		
			// newProducts[index].qty--;
		
			this.setState({
				products:newProducts
			});
		}
		
		
	}


}